In [15]:
#샘플 데이터로부터 가장 가까운 k개의 이웃 찾기

from sklearn.datasets import load_iris
from sklearn.neighbors import  NearestNeighbors
from sklearn.preprocessing import StandardScaler

iris = load_iris()
features = iris.data
#특성 정규화 평균이 0 표준편차1
features_standard = StandardScaler().fit_transform(features)

nearest_neighbors = NearestNeighbors(n_neighbors=2).fit(features_standard)
new_observation = [1,1,1,1]
#새로운 샘플 데이터의 최근접 이웃의 인덱스와 거리 반환
distances, indices = nearest_neighbors.kneighbors([new_observation]) 
print(features_standard [indices])   #최근접 이웃 확인 
print(distances)

[[[1.03800476 0.55861082 1.10378283 1.18556721]
  [0.79566902 0.32841405 0.76275827 1.05393502]]]
[[0.49140089 0.74294782]]


In [27]:
nearest_neighbors_euclidean= NearestNeighbors(n_neighbors=2,  metric='euclidean' ).fit(features_standard)
distances, indices = nearest_neighbors_euclidean.kneighbors([new_observation]) 
print(features_standard [indices])   #최근접 이웃 확인 
print(distances)

# 디폴트값이 유클리디언

[[[1.03800476 0.55861082 1.10378283 1.18556721]
  [0.79566902 0.32841405 0.76275827 1.05393502]]]
[[0.49140089 0.74294782]]


In [21]:
nn_euclidean = NearestNeighbors(n_neighbors=3, metric='euclidean').fit(features_standard)
 
#새로운 샘플 데이터의 최근접 이웃의 인덱스와 거리 반환
distances, indices = nn_euclidean.kneighbors([new_observation]) 
print(features_standard [indices])   #최근접 이웃 확인 
print(distances)

[[[1.03800476 0.55861082 1.10378283 1.18556721]
  [0.79566902 0.32841405 0.76275827 1.05393502]
  [0.4321654  0.78880759 0.93327055 1.44883158]]]
[[0.49140089 0.74294782 0.75692864]]


In [22]:
nn_with_self = nn_euclidean.kneighbors_graph(features_standard).toarray()
#최근접 이웃 중에서 1로 표시된 자기 자신을 제외시킵니다.
for i, x in enumerate(nn_with_self) :
    x[i] = 0

print(nn_with_self[0]) #첫번째 샘플에 대한 최근접 이웃 확인

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


In [23]:
#샘플과 가까운 최근접 이웃 5개 인덱스 찾기
indices = nn_euclidean.kneighbors([new_observation], n_neighbors=5, return_distance=False)
features_standard[indices]

array([[[1.03800476, 0.55861082, 1.10378283, 1.18556721],
        [0.79566902, 0.32841405, 0.76275827, 1.05393502],
        [0.4321654 , 0.78880759, 0.93327055, 1.44883158],
        [0.55333328, 0.78880759, 1.0469454 , 1.58046376],
        [1.03800476, 0.55861082, 1.10378283, 1.71209594]]])

In [40]:
import numpy as np

# 반경 0.5 안에 있는 모든 샘플의 인덱스를 찾습니다.
nn_with_self = nn_euclidean.radius_neighbors_graph([new_observation], radius = 0.5).toarray()
# features_standard[indices] 
nn_with_self # 1개 
# 첫번째 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.]])