In [1]:
import numpy as np
from scipy import sparse

matrix = np.array([[0,0],
                  [0,1],
                  [3,0]])
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [4]:
matrix_sparse_2 = sparse.csr_matrix(([1,3], ([1,2],[1,0])), shape=(3,10))
print(matrix_sparse_2)

  (1, 1)	1
  (2, 0)	3


In [6]:
import numpy as np
vector = np.array([1, 2 ,3 , 4, 5, 6])
matrix = np.array( [ [ 1, 2, 3],  [ 4, 5, 6], [ 7, 8, 9] ])

In [7]:
vector[2]

3

In [8]:
matrix[1, 1] 

5

In [9]:
vector[ : ]  #벡터에 있는 모든 원소를 선택합니다.

array([1, 2, 3, 4, 5, 6])

In [10]:
vector[ : 3]  #세 번째 원소를 포함하여 모든 원소를 선택합니다.

array([1, 2, 3])

In [11]:
vector[3: ]  #세 번째 이후의 모든 원소를 선택합니다.

array([4, 5, 6])

In [12]:
vector[-1]

6

In [13]:
matrix[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
matrix[:, 1:2]

array([[2],
       [5],
       [8]])

In [15]:
matrix[[0, 2]]  # 0행, 2행

array([[1, 2, 3],
       [7, 8, 9]])

In [16]:
matrix[[0,2], [1,0]]  # (0,1)요소, (2,0)요소

array([2, 7])

In [19]:
mask = matrix > 5
matrix[mask]

array([6, 7, 8, 9])

In [20]:
import numpy as np
matrix = np.array( [ [ 1, 2, 3, 4],  [ 5, 6, 7, 8], [9, 10, 11, 12 ] ])
 
matrix.shape
matrix.size
matrix.ndim
matrix.dtype   #원소의 데이터 타입 확인
matrix.itemsize   #원소 하나가 차지하는 바이트 크기
matrix.nbytes  # 배열 전체가 차지하는 바이트 크기


48

In [23]:
import numpy as np

matrix = np.array( [ [ 1, 2, 3],  [ 4, 5, 6], [ 7, 8, 9]  ])
matrix.T
np.array([1, 2, 3, 4, 5, 6] ).T   #벡터는 값의 모음이기 때문에 전치 할 수 없음
np.array([ [ 1, 2, 3, 4, 5, 6]  ] ).T    #행 벡터를 열 벡터로 전치
matrix.transpose()  
matrix = np.array([ [ [1, 2] ,[ 3, 4 ], [5, 6]  ],
            [ [7, 8 ], [9, 10 ], [11, 12] ] ])  #2x3x2 행렬
matrix.transpose((0, 2, 1))  #2x2x3 행렬로 변환

array([[[ 1,  3,  5],
        [ 2,  4,  6]],

       [[ 7,  9, 11],
        [ 8, 10, 12]]])

In [27]:
import numpy as np

matrix = np.array( [ [ 1, 2, 3],  [ 4, 5, 6], [ 7, 8, 9]  ])
matrix.flatten()  # 새로운 배열을 만들어준다
matrix.reshape(1, -1)  # numpy배열의 view를 반환한다
                       # matrix을 가상화해서 1차원으로 만들어준다
vector_reshaped = matrix.reshape( -1)
vector_flattened = matrix.flatten()
matrix[0][0] = -1
vector_reshaped 
vector_flattened

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
import numpy as np

matrix = np.array( [ [ 1, 1, 1],  [ 1, 1, 10], [ 1, 1, 15]  ])
display(matrix)
np.linalg.matrix_rank(matrix)  #행렬은 첫번째 열과 두번째 열이 동일하기 때문에 독립적인 열이 2개

array([[ 1,  1,  1],
       [ 1,  1, 10],
       [ 1,  1, 15]])

2

In [31]:
s = np.linalg.svd(matrix, compute_uv = False)  #svd 함수로 특잇값만 계산
np.sum(s > 1e-10)  #오차를 고려하여 0에 가까운 아주 작은 값을 지정

2

In [32]:
import numpy as np

matrix = np.array( [ [ 1, 2, 3],  [ 2, 4, 6], [ 3, 8, 9]  ])
np.linalg.det(matrix) #행렬의 행렬식 반환

0.0

In [34]:
import numpy as np

matrix = np.array( [ [ 1, 2, 3],  [ 2, 4, 6], [ 3, 8, 9]  ])
matrix.diagonal()

array([1, 4, 9])

In [35]:
matrix.diagonal(offset=1)  #주 대각선 하나 위의 대각원소를 반환

array([2, 6])

In [36]:
matrix.diagonal(offset=-1)  #주 대각선 하나 아래의 대각원소를 반환

array([2, 8])

In [37]:
a = matrix.diagonal().copy()  #반환된 배열을 변경하려면 복사
a = np.diag(matrix)